@startuml
!include_many common/init.puml

activate Client

alt QR-code
	Client -> NoticeSrv ++ : PATCH /paymentNotices///<qr code>//
		note left
			!include_many request/activate.frag
		end note

		NoticeSrv -> NoticeSrv : parse //<qr code>//: //<pa tax code>//, //<notice number>//
else w/o QR-code
	Client -> NoticeSrv : PATCH /paymentNotices///<pa tax code>/////<notice number>//
		note left
			!include_many request/activate.frag
		end note
end

!include_many common/get_config_from_azure_blob_storage.puml

alt ok
	!include_many nodo_interaction/activate_ok.puml

	group Store data in the cache
		NoticeSrv -> NoticeCache ++ : set(//<payment token>//, //<value>//)
			note left
				!include_many common/stored_notice_data.frag
			end note

		NoticeCache --> NoticeSrv -- : ok
	end
	
	note over NoticeSrv #Orange
		On any failure, return HTTP 500 (server error) with specific error body. 
	end note

	NoticeSrv --> Client : HTTP 200 (ok)
		note right
			!include_many response/activate_ok.frag
		end note
else ko
	!include_many nodo_interaction/activate_ko.puml

	NoticeSrv --> Client -- : HTTP 200 (ok)
		note right
			!include_many response/activate_ok.frag
		end note
end

note over NoticeSrv #Orange
	On any other failure while communicating with Nodo, return HTTP 500 (server error) with specific error body.
end note

deactivate Client
@enduml
 