package it.gov.pagopa.pagopa_api.nodeforpsp;

import java.util.concurrent.Future;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.AsyncHandler;
import javax.xml.ws.Response;

/**
 * This class was generated by Apache CXF 3.5.5
 * 2023-02-06T16:09:24.684+01:00
 * Generated source version: 3.5.5
 *
 */
@WebService(targetNamespace = "http://pagopa-api.pagopa.gov.it/nodeForPsp", name = "nodeForPsp")
@XmlSeeAlso({it.gov.pagopa.pagopa_api.node.nodeforpsp.ObjectFactory.class, it.gov.pagopa.pagopa_api.xsd.common_types.v1_0.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface NodeForPsp {

    @WebMethod(operationName = "verificaBollettino")
    public Response<it.gov.pagopa.pagopa_api.node.nodeforpsp.VerificaBollettinoRes> verificaBollettinoAsync(

        @WebParam(partName = "bodyrequest", name = "verificaBollettinoReq", targetNamespace = "http://pagopa-api.pagopa.gov.it/node/nodeForPsp.xsd")
        it.gov.pagopa.pagopa_api.node.nodeforpsp.VerificaBollettinoReq bodyrequest
    );

    @WebMethod(operationName = "verificaBollettino")
    public Future<?> verificaBollettinoAsync(

        @WebParam(partName = "bodyrequest", name = "verificaBollettinoReq", targetNamespace = "http://pagopa-api.pagopa.gov.it/node/nodeForPsp.xsd")
        it.gov.pagopa.pagopa_api.node.nodeforpsp.VerificaBollettinoReq bodyrequest,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<it.gov.pagopa.pagopa_api.node.nodeforpsp.VerificaBollettinoRes> asyncHandler
    );

    @WebMethod(action = "verificaBollettino")
    @WebResult(name = "verificaBollettinoRes", targetNamespace = "http://pagopa-api.pagopa.gov.it/node/nodeForPsp.xsd", partName = "bodyresponse")
    public it.gov.pagopa.pagopa_api.node.nodeforpsp.VerificaBollettinoRes verificaBollettino(

        @WebParam(partName = "bodyrequest", name = "verificaBollettinoReq", targetNamespace = "http://pagopa-api.pagopa.gov.it/node/nodeForPsp.xsd")
        it.gov.pagopa.pagopa_api.node.nodeforpsp.VerificaBollettinoReq bodyrequest
    );

    @WebMethod(operationName = "activatePaymentNoticeV2")
    public Response<it.gov.pagopa.pagopa_api.node.nodeforpsp.ActivatePaymentNoticeV2Response> activatePaymentNoticeV2Async(

        @WebParam(partName = "bodyrequest", name = "activatePaymentNoticeV2Request", targetNamespace = "http://pagopa-api.pagopa.gov.it/node/nodeForPsp.xsd")
        it.gov.pagopa.pagopa_api.node.nodeforpsp.ActivatePaymentNoticeV2Request bodyrequest
    );

    @WebMethod(operationName = "activatePaymentNoticeV2")
    public Future<?> activatePaymentNoticeV2Async(

        @WebParam(partName = "bodyrequest", name = "activatePaymentNoticeV2Request", targetNamespace = "http://pagopa-api.pagopa.gov.it/node/nodeForPsp.xsd")
        it.gov.pagopa.pagopa_api.node.nodeforpsp.ActivatePaymentNoticeV2Request bodyrequest,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<it.gov.pagopa.pagopa_api.node.nodeforpsp.ActivatePaymentNoticeV2Response> asyncHandler
    );

    @WebMethod(action = "activatePaymentNoticeV2")
    @WebResult(name = "activatePaymentNoticeV2Response", targetNamespace = "http://pagopa-api.pagopa.gov.it/node/nodeForPsp.xsd", partName = "bodyresponse")
    public it.gov.pagopa.pagopa_api.node.nodeforpsp.ActivatePaymentNoticeV2Response activatePaymentNoticeV2(

        @WebParam(partName = "bodyrequest", name = "activatePaymentNoticeV2Request", targetNamespace = "http://pagopa-api.pagopa.gov.it/node/nodeForPsp.xsd")
        it.gov.pagopa.pagopa_api.node.nodeforpsp.ActivatePaymentNoticeV2Request bodyrequest
    );

    @WebMethod(operationName = "nodoChiediCatalogoServiziV2")
    public Response<it.gov.pagopa.pagopa_api.node.nodeforpsp.NodoChiediCatalogoServiziV2Response> nodoChiediCatalogoServiziV2Async(

        @WebParam(partName = "bodyrequest", name = "nodoChiediCatalogoServiziV2Request", targetNamespace = "http://pagopa-api.pagopa.gov.it/node/nodeForPsp.xsd")
        it.gov.pagopa.pagopa_api.node.nodeforpsp.NodoChiediCatalogoServiziV2Request bodyrequest
    );

    @WebMethod(operationName = "nodoChiediCatalogoServiziV2")
    public Future<?> nodoChiediCatalogoServiziV2Async(

        @WebParam(partName = "bodyrequest", name = "nodoChiediCatalogoServiziV2Request", targetNamespace = "http://pagopa-api.pagopa.gov.it/node/nodeForPsp.xsd")
        it.gov.pagopa.pagopa_api.node.nodeforpsp.NodoChiediCatalogoServiziV2Request bodyrequest,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<it.gov.pagopa.pagopa_api.node.nodeforpsp.NodoChiediCatalogoServiziV2Response> asyncHandler
    );

    @WebMethod(action = "nodoChiediCatalogoServiziV2")
    @WebResult(name = "nodoChiediCatalogoServiziV2Response", targetNamespace = "http://pagopa-api.pagopa.gov.it/node/nodeForPsp.xsd", partName = "bodyresponse")
    public it.gov.pagopa.pagopa_api.node.nodeforpsp.NodoChiediCatalogoServiziV2Response nodoChiediCatalogoServiziV2(

        @WebParam(partName = "bodyrequest", name = "nodoChiediCatalogoServiziV2Request", targetNamespace = "http://pagopa-api.pagopa.gov.it/node/nodeForPsp.xsd")
        it.gov.pagopa.pagopa_api.node.nodeforpsp.NodoChiediCatalogoServiziV2Request bodyrequest
    );

    @WebMethod(operationName = "verifyPaymentNotice")
    public Response<it.gov.pagopa.pagopa_api.node.nodeforpsp.VerifyPaymentNoticeRes> verifyPaymentNoticeAsync(

        @WebParam(partName = "bodyrequest", name = "verifyPaymentNoticeReq", targetNamespace = "http://pagopa-api.pagopa.gov.it/node/nodeForPsp.xsd")
        it.gov.pagopa.pagopa_api.node.nodeforpsp.VerifyPaymentNoticeReq bodyrequest
    );

    @WebMethod(operationName = "verifyPaymentNotice")
    public Future<?> verifyPaymentNoticeAsync(

        @WebParam(partName = "bodyrequest", name = "verifyPaymentNoticeReq", targetNamespace = "http://pagopa-api.pagopa.gov.it/node/nodeForPsp.xsd")
        it.gov.pagopa.pagopa_api.node.nodeforpsp.VerifyPaymentNoticeReq bodyrequest,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<it.gov.pagopa.pagopa_api.node.nodeforpsp.VerifyPaymentNoticeRes> asyncHandler
    );

    @WebMethod(action = "verifyPaymentNotice")
    @WebResult(name = "verifyPaymentNoticeRes", targetNamespace = "http://pagopa-api.pagopa.gov.it/node/nodeForPsp.xsd", partName = "bodyresponse")
    public it.gov.pagopa.pagopa_api.node.nodeforpsp.VerifyPaymentNoticeRes verifyPaymentNotice(

        @WebParam(partName = "bodyrequest", name = "verifyPaymentNoticeReq", targetNamespace = "http://pagopa-api.pagopa.gov.it/node/nodeForPsp.xsd")
        it.gov.pagopa.pagopa_api.node.nodeforpsp.VerifyPaymentNoticeReq bodyrequest
    );

    @WebMethod(operationName = "nodoChiediTemplateInformativaPSP")
    public Response<it.gov.pagopa.pagopa_api.node.nodeforpsp.NodoChiediTemplateInformativaPSPResponse> nodoChiediTemplateInformativaPSPAsync(

        @WebParam(partName = "bodyrequest", name = "nodoChiediTemplateInformativaPSPRequest", targetNamespace = "http://pagopa-api.pagopa.gov.it/node/nodeForPsp.xsd")
        it.gov.pagopa.pagopa_api.node.nodeforpsp.NodoChiediTemplateInformativaPSPRequest bodyrequest
    );

    @WebMethod(operationName = "nodoChiediTemplateInformativaPSP")
    public Future<?> nodoChiediTemplateInformativaPSPAsync(

        @WebParam(partName = "bodyrequest", name = "nodoChiediTemplateInformativaPSPRequest", targetNamespace = "http://pagopa-api.pagopa.gov.it/node/nodeForPsp.xsd")
        it.gov.pagopa.pagopa_api.node.nodeforpsp.NodoChiediTemplateInformativaPSPRequest bodyrequest,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<it.gov.pagopa.pagopa_api.node.nodeforpsp.NodoChiediTemplateInformativaPSPResponse> asyncHandler
    );

    @WebMethod(action = "nodoChiediTemplateInformativaPSP")
    @WebResult(name = "nodoChiediTemplateInformativaPSPResponse", targetNamespace = "http://pagopa-api.pagopa.gov.it/node/nodeForPsp.xsd", partName = "bodyresponse")
    public it.gov.pagopa.pagopa_api.node.nodeforpsp.NodoChiediTemplateInformativaPSPResponse nodoChiediTemplateInformativaPSP(

        @WebParam(partName = "bodyrequest", name = "nodoChiediTemplateInformativaPSPRequest", targetNamespace = "http://pagopa-api.pagopa.gov.it/node/nodeForPsp.xsd")
        it.gov.pagopa.pagopa_api.node.nodeforpsp.NodoChiediTemplateInformativaPSPRequest bodyrequest
    );

    @WebMethod(operationName = "activatePaymentNotice")
    public Response<it.gov.pagopa.pagopa_api.node.nodeforpsp.ActivatePaymentNoticeRes> activatePaymentNoticeAsync(

        @WebParam(partName = "bodyrequest", name = "activatePaymentNoticeReq", targetNamespace = "http://pagopa-api.pagopa.gov.it/node/nodeForPsp.xsd")
        it.gov.pagopa.pagopa_api.node.nodeforpsp.ActivatePaymentNoticeReq bodyrequest
    );

    @WebMethod(operationName = "activatePaymentNotice")
    public Future<?> activatePaymentNoticeAsync(

        @WebParam(partName = "bodyrequest", name = "activatePaymentNoticeReq", targetNamespace = "http://pagopa-api.pagopa.gov.it/node/nodeForPsp.xsd")
        it.gov.pagopa.pagopa_api.node.nodeforpsp.ActivatePaymentNoticeReq bodyrequest,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<it.gov.pagopa.pagopa_api.node.nodeforpsp.ActivatePaymentNoticeRes> asyncHandler
    );

    @WebMethod(action = "activatePaymentNotice")
    @WebResult(name = "activatePaymentNoticeRes", targetNamespace = "http://pagopa-api.pagopa.gov.it/node/nodeForPsp.xsd", partName = "bodyresponse")
    public it.gov.pagopa.pagopa_api.node.nodeforpsp.ActivatePaymentNoticeRes activatePaymentNotice(

        @WebParam(partName = "bodyrequest", name = "activatePaymentNoticeReq", targetNamespace = "http://pagopa-api.pagopa.gov.it/node/nodeForPsp.xsd")
        it.gov.pagopa.pagopa_api.node.nodeforpsp.ActivatePaymentNoticeReq bodyrequest
    );

    @WebMethod(operationName = "sendPaymentOutcomeV2")
    public Response<it.gov.pagopa.pagopa_api.node.nodeforpsp.SendPaymentOutcomeV2Response> sendPaymentOutcomeV2Async(

        @WebParam(partName = "bodyrequest", name = "sendPaymentOutcomeV2Request", targetNamespace = "http://pagopa-api.pagopa.gov.it/node/nodeForPsp.xsd")
        it.gov.pagopa.pagopa_api.node.nodeforpsp.SendPaymentOutcomeV2Request bodyrequest
    );

    @WebMethod(operationName = "sendPaymentOutcomeV2")
    public Future<?> sendPaymentOutcomeV2Async(

        @WebParam(partName = "bodyrequest", name = "sendPaymentOutcomeV2Request", targetNamespace = "http://pagopa-api.pagopa.gov.it/node/nodeForPsp.xsd")
        it.gov.pagopa.pagopa_api.node.nodeforpsp.SendPaymentOutcomeV2Request bodyrequest,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<it.gov.pagopa.pagopa_api.node.nodeforpsp.SendPaymentOutcomeV2Response> asyncHandler
    );

    @WebMethod(action = "sendPaymentOutcomeV2")
    @WebResult(name = "sendPaymentOutcomeV2Response", targetNamespace = "http://pagopa-api.pagopa.gov.it/node/nodeForPsp.xsd", partName = "bodyresponse")
    public it.gov.pagopa.pagopa_api.node.nodeforpsp.SendPaymentOutcomeV2Response sendPaymentOutcomeV2(

        @WebParam(partName = "bodyrequest", name = "sendPaymentOutcomeV2Request", targetNamespace = "http://pagopa-api.pagopa.gov.it/node/nodeForPsp.xsd")
        it.gov.pagopa.pagopa_api.node.nodeforpsp.SendPaymentOutcomeV2Request bodyrequest
    );

    @WebMethod(operationName = "nodoInviaFlussoRendicontazione")
    public Response<it.gov.pagopa.pagopa_api.node.nodeforpsp.NodoInviaFlussoRendicontazioneResponse> nodoInviaFlussoRendicontazioneAsync(

        @WebParam(partName = "bodyrequest", name = "nodoInviaFlussoRendicontazioneRequest", targetNamespace = "http://pagopa-api.pagopa.gov.it/node/nodeForPsp.xsd")
        it.gov.pagopa.pagopa_api.node.nodeforpsp.NodoInviaFlussoRendicontazioneRequest bodyrequest
    );

    @WebMethod(operationName = "nodoInviaFlussoRendicontazione")
    public Future<?> nodoInviaFlussoRendicontazioneAsync(

        @WebParam(partName = "bodyrequest", name = "nodoInviaFlussoRendicontazioneRequest", targetNamespace = "http://pagopa-api.pagopa.gov.it/node/nodeForPsp.xsd")
        it.gov.pagopa.pagopa_api.node.nodeforpsp.NodoInviaFlussoRendicontazioneRequest bodyrequest,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<it.gov.pagopa.pagopa_api.node.nodeforpsp.NodoInviaFlussoRendicontazioneResponse> asyncHandler
    );

    @WebMethod(action = "nodoInviaFlussoRendicontazione")
    @WebResult(name = "nodoInviaFlussoRendicontazioneResponse", targetNamespace = "http://pagopa-api.pagopa.gov.it/node/nodeForPsp.xsd", partName = "bodyresponse")
    public it.gov.pagopa.pagopa_api.node.nodeforpsp.NodoInviaFlussoRendicontazioneResponse nodoInviaFlussoRendicontazione(

        @WebParam(partName = "bodyrequest", name = "nodoInviaFlussoRendicontazioneRequest", targetNamespace = "http://pagopa-api.pagopa.gov.it/node/nodeForPsp.xsd")
        it.gov.pagopa.pagopa_api.node.nodeforpsp.NodoInviaFlussoRendicontazioneRequest bodyrequest
    );

    @WebMethod(operationName = "nodoChiediInformativaPA")
    public Response<it.gov.pagopa.pagopa_api.node.nodeforpsp.NodoChiediInformativaPAResponse> nodoChiediInformativaPAAsync(

        @WebParam(partName = "bodyrequest", name = "nodoChiediInformativaPARequest", targetNamespace = "http://pagopa-api.pagopa.gov.it/node/nodeForPsp.xsd")
        it.gov.pagopa.pagopa_api.node.nodeforpsp.NodoChiediInformativaPARequest bodyrequest
    );

    @WebMethod(operationName = "nodoChiediInformativaPA")
    public Future<?> nodoChiediInformativaPAAsync(

        @WebParam(partName = "bodyrequest", name = "nodoChiediInformativaPARequest", targetNamespace = "http://pagopa-api.pagopa.gov.it/node/nodeForPsp.xsd")
        it.gov.pagopa.pagopa_api.node.nodeforpsp.NodoChiediInformativaPARequest bodyrequest,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<it.gov.pagopa.pagopa_api.node.nodeforpsp.NodoChiediInformativaPAResponse> asyncHandler
    );

    @WebMethod(action = "nodoChiediInformativaPA")
    @WebResult(name = "nodoChiediInformativaPAResponse", targetNamespace = "http://pagopa-api.pagopa.gov.it/node/nodeForPsp.xsd", partName = "bodyresponse")
    public it.gov.pagopa.pagopa_api.node.nodeforpsp.NodoChiediInformativaPAResponse nodoChiediInformativaPA(

        @WebParam(partName = "bodyrequest", name = "nodoChiediInformativaPARequest", targetNamespace = "http://pagopa-api.pagopa.gov.it/node/nodeForPsp.xsd")
        it.gov.pagopa.pagopa_api.node.nodeforpsp.NodoChiediInformativaPARequest bodyrequest
    );

    @WebMethod(operationName = "sendPaymentOutcome")
    public Response<it.gov.pagopa.pagopa_api.node.nodeforpsp.SendPaymentOutcomeRes> sendPaymentOutcomeAsync(

        @WebParam(partName = "bodyrequest", name = "sendPaymentOutcomeReq", targetNamespace = "http://pagopa-api.pagopa.gov.it/node/nodeForPsp.xsd")
        it.gov.pagopa.pagopa_api.node.nodeforpsp.SendPaymentOutcomeReq bodyrequest
    );

    @WebMethod(operationName = "sendPaymentOutcome")
    public Future<?> sendPaymentOutcomeAsync(

        @WebParam(partName = "bodyrequest", name = "sendPaymentOutcomeReq", targetNamespace = "http://pagopa-api.pagopa.gov.it/node/nodeForPsp.xsd")
        it.gov.pagopa.pagopa_api.node.nodeforpsp.SendPaymentOutcomeReq bodyrequest,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<it.gov.pagopa.pagopa_api.node.nodeforpsp.SendPaymentOutcomeRes> asyncHandler
    );

    @WebMethod(action = "sendPaymentOutcome")
    @WebResult(name = "sendPaymentOutcomeRes", targetNamespace = "http://pagopa-api.pagopa.gov.it/node/nodeForPsp.xsd", partName = "bodyresponse")
    public it.gov.pagopa.pagopa_api.node.nodeforpsp.SendPaymentOutcomeRes sendPaymentOutcome(

        @WebParam(partName = "bodyrequest", name = "sendPaymentOutcomeReq", targetNamespace = "http://pagopa-api.pagopa.gov.it/node/nodeForPsp.xsd")
        it.gov.pagopa.pagopa_api.node.nodeforpsp.SendPaymentOutcomeReq bodyrequest
    );

    @WebMethod(operationName = "demandPaymentNotice")
    public Response<it.gov.pagopa.pagopa_api.node.nodeforpsp.DemandPaymentNoticeResponse> demandPaymentNoticeAsync(

        @WebParam(partName = "bodyrequest", name = "demandPaymentNoticeRequest", targetNamespace = "http://pagopa-api.pagopa.gov.it/node/nodeForPsp.xsd")
        it.gov.pagopa.pagopa_api.node.nodeforpsp.DemandPaymentNoticeRequest bodyrequest
    );

    @WebMethod(operationName = "demandPaymentNotice")
    public Future<?> demandPaymentNoticeAsync(

        @WebParam(partName = "bodyrequest", name = "demandPaymentNoticeRequest", targetNamespace = "http://pagopa-api.pagopa.gov.it/node/nodeForPsp.xsd")
        it.gov.pagopa.pagopa_api.node.nodeforpsp.DemandPaymentNoticeRequest bodyrequest,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<it.gov.pagopa.pagopa_api.node.nodeforpsp.DemandPaymentNoticeResponse> asyncHandler
    );

    @WebMethod(action = "demandPaymentNotice")
    @WebResult(name = "demandPaymentNoticeResponse", targetNamespace = "http://pagopa-api.pagopa.gov.it/node/nodeForPsp.xsd", partName = "bodyresponse")
    public it.gov.pagopa.pagopa_api.node.nodeforpsp.DemandPaymentNoticeResponse demandPaymentNotice(

        @WebParam(partName = "bodyrequest", name = "demandPaymentNoticeRequest", targetNamespace = "http://pagopa-api.pagopa.gov.it/node/nodeForPsp.xsd")
        it.gov.pagopa.pagopa_api.node.nodeforpsp.DemandPaymentNoticeRequest bodyrequest
    );
}
