package it.gov.pagopa.pagopa_api.nodeforpsp;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.5.1
 * 2023-01-23T17:33:33.470+01:00
 * Generated source version: 3.5.1
 *
 */
@WebServiceClient(name = "nodeForPspService",
                  wsdlLocation = "file:/C:/Users/fabrizio.guerrini/workspaceQuarkus/mil-payment-notice/src/main/resources/nodeForPsp.wsdl",
                  targetNamespace = "http://pagopa-api.pagopa.gov.it/nodeForPsp")
public class NodeForPspService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://pagopa-api.pagopa.gov.it/nodeForPsp", "nodeForPspService");
    public final static QName NodeForPspPort = new QName("http://pagopa-api.pagopa.gov.it/nodeForPsp", "nodeForPspPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/fabrizio.guerrini/workspaceQuarkus/mil-payment-notice/src/main/resources/nodeForPsp.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(NodeForPspService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/fabrizio.guerrini/workspaceQuarkus/mil-payment-notice/src/main/resources/nodeForPsp.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public NodeForPspService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public NodeForPspService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NodeForPspService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public NodeForPspService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public NodeForPspService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public NodeForPspService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns NodeForPsp
     */
    @WebEndpoint(name = "nodeForPspPort")
    public NodeForPsp getNodeForPspPort() {
        return super.getPort(NodeForPspPort, NodeForPsp.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NodeForPsp
     */
    @WebEndpoint(name = "nodeForPspPort")
    public NodeForPsp getNodeForPspPort(WebServiceFeature... features) {
        return super.getPort(NodeForPspPort, NodeForPsp.class, features);
    }

}
