!pragma teoz true
hide unlinked
skinparam style strictuml
skinparam maxMessageSize 200
skinparam shadowing false
skinparam sequenceMessageAlign center
skinparam sequenceLifeLineBackgroundColor GreenYellow
autonumber "<font color='blue'><b><u>##</u></b></font>"

sprite $AzureContainerApp [70x70/16z] {
	xPY7SkCW48RP3lBxl-y5ybyirbZuUlscUGZwl6qcAvSV3ecQMRYPYj3vl9-yP52BX78PI0oSTmxnM69Iojr-7Ou6S3CHPX4pQArmtA5j7Axf3lSWk407vnF8
	tnNBfDaAnGbVAb0vlqYOuqnPOeZpMopaBpJmEYD8j6pOL1UI7NmToXC9BQO9yBgmcWIY7j6SrWErc3cT94HY7k-quwXAiqUj3nJpOxQuIImM09OtRbKNN-mF
	HU6H0GJ9qZMtMqgO7fea4VrqIOEa4vBcd5D_UbAPKPfZS0F7IUHpizLDayKxiDmbrOtdd1O5nkFPCgWcZFwRLnSqrazILYjSQ-3PywVQ5OPhWlxtG-zICVwO
	hCwmW8zFi4Hktr0VhOi60IujLg2OBH1bIyMTrooWAdsh1Q9lj80_olBVqjfdIsi1Mcj_XUN-wTTP6jBuRudlO74gtsgfYeLZR_6YlhGuJrjAjnn7guE-Qu1Z
	qFezLfyjJVkfJ0lF4ml00anY3alq0_NJ_YtKhVZUjhBq__FLf7HOBOnG3fjs28C5jBC5civnjNhug4kYlJ5B3aVyQVC0FAHiqOu5q3HzN0KfRvYAjoklAycn
	t5IIbqxHBO926CidijccMuAWqDICBzTcoG5Yqb3HrP8jotCRWwooUco_gGFzsF5ruo18rbW0tx_XskxTDTt9w6Mu52VuCf3Wvu52S5KQ7WwdJQHNAP7wllWs
	MrWuZGx-GkKAcIqIWPyxpCm36B_qNWa4eKsulZYGzu7Hf37byXAUViqW4RKtH2G5iPjiTFAR43CtAR-6Jm
}

sprite $AzureActiveDirectory [70x70/16z] {
	vTZBRYin30FGw64v-VyFlhTrX25g8X0KPnUkkZfWX_CmSll2w2SGyV41nJty0uX7s25YImazHPOISZAFftB2Y4E94mJAU7yUXn9-X7WSC4RA6tkhinBIHaYP
	SpOPSLBcRw9xPP4asenloaH6Rnva_edt4IY8DUOX1T76FAGWqa2Wz1clbNflgvNxJwAD-8QiZCOyfDolM75bAOIiQ0intuY2OS7CL8sKZ9H82gfG29h5F0bi
	2ad120cai3HeO_mJXGBfyV1j7W9OuMotZS1eAFoMq7Uwy7CWrbJokoAIyxYWJg7G2zZdl3RMz0g5YkZw4yynrM65N-7ZETJ08sXR7LBeNMVN7UXP1NN42YNd
	bS1TZ3Aeewpml0xZgIeStUgm4d8LsHycepgl5ASYaaPHntXU5F4NRmOQtMZUD504aLTrZEQbxq1L1uhjLpNgZu2XZc5UWx5K2jNHhBEKd9VVbNMTXEsQ5qNq
	LaIfJiwB8juy1brB3XYOjrU7v-MKeqjC-f2rwnXwe4YxphZplFqwW-RjnQ0qY_3eW-PjnvwAd_zOWNaFOdRxmlm7
}

sprite $AzureBlobStorage [70x70/16z] {
	xT853WCn34JH92QfzpzmPL4PHfCKTlqEy0DsmvGoX39QiY1fLeBbV2NzSwKgLL5QLZejAuCslz9XzoeDzcULgj2o8hG55GNThGHiPQKgkkmk2fk_kqexhtY0
	_5xb0DjUnLPLZAXC_nTpaDrKA5anshoA64bQ6gI6AUK8
}

sprite $AzureRedisCache [70x70/16z] {
	xTG5cYGX30LW8aJW_lVT8hHhQcsCVwJjVSbhe_ocPO6ptul01X5fGiJ8xOh4myJNA6BPI2I87w78f2AnXX-BLUa8y5074ObB7Y0VKOXLejSare0c8zqH8aMn
	PswYmttUiv7UdU4HzjxJaT242Sw8fVMmAnBQKG-F8drl9BFeuxkiBkuZulwRNPh5j-GCMMnd5-LvB9rXZ6JBTt42GE8xX03aoIu-ma_F9FHS5ndLdm00oNKn
	c4_eS9QewZnHU7wbBTUbAyxtHFI2L8wxjUUwR9VrUBOHCTC68M2DKAhBuC9mWyNxaEuoDJCHseYOdU_ETNdnbSXrIKpv0btaJxj86UJFkaYPeBRVxT8gb3DW
	iRQpYob3UG1mqDTJ54DvGrvFaVBMchAch2dyUWgN77yrnKfMRS-cj5fs86ttKvfIsGkegfcrpNOX5Q7y5Slo2m
}

sprite $AzureCosmosDb [70x70/16z] {
	pPS7WkCW34MjWX3S_y0x16SLFk0jzfOtlRtH5qI4u_z4df2GqWCMLduYaCeJWVI1IDgudwSXD-DqReHYqK_aUgc8HLw_9ap32YDl3INBNcejxecxG4Taq7yg
	wAqeTI3h2XvIOHcvpfGVQcZehTO0FS9C3PQ5HY8cUJqfRoBNl3rms_LFk0mA41N6Hl3gSIJeG0zZWiLZMWS7UjnICePsplD51WcY_JS9B8EclLrA-5qsWGLm
	aFX9QSWyN1dw4ljaS0J55ZDQLfRoAN508Nq3nm2MuXCy_6fiksqfACc9UqUX6DXqiTzMaaJ71EzAiKKf-GkZzHb8K0e62aU3ZmMq6VWKWGQ9NGtQgKnTIxAk
	BPj3Gnh9_ESiQISvWra9oTQYBwuE-tHfkPQ4vR31OZi9hGv73kLWoRoJ8D2gqMAyQApE9GfOyc39zlb_gKjyiZ2UpwpsqWH9EocTafgMEGyUpJPOidUwBdcj
	iif31q73iyyIqyRh2D-rbY6dEqfII7nL2ZpXZMrpAg8GjIR1jiJ0cWOepBikoULbmVonb-T8mUb8tYLv4KZGWhLO58Abu660dKaH9Wh1Kj22dI5qv7ZcG5iB
	5cFbY-yEDG-97XiBQgX9UZ_EC26nGO3TZGwBUYdP51nTuiSCmwpmsYZU5D6GSDH2sn7A7ve84lq8YLzV0hWZ-a6oK4mI1isQP5vhURrquE6ZX9gr0iaqj8Ad
	XHeGvZmxYk2o70YBg8h4XOLq4EN4Spj3UuMax9ujAM_MX8yxn6M8w7STh0E_NGf9tChkNrZbk0dTbiH-kO_A8nP-mYB7_yWt
}

sprite $AzureEventHub [70x70/16z] {
	xTS5RWHH281XdFlVk1dXfTG9NUUBxOxyumONDdX3M4QyWPrwasuLRxjIPIe4PNIRobIG0bOgvXjRepG8_4RZcawAbV2I5JorAkO12ZwUBxv0mpDKC7Ggx44-
	LyW3_QaILvdeIV98BbMogKH5rhzIXInDw4iQQGG5SpLkyWxarjKODDqnhL59T-z6fQ1VGTbWjP9dZVs7zGh6Vi_lBxaYdNSf3D2eP5DXBEChVTbCnRp9tjre
	JSlic0_XeiOR
}

participant "Client" as Client

box Multichannel Integration Layer #GhostWhite
	participant "mil-payment-notice\n<$AzureContainerApp,scale=0.5,color=DodgerBlue>" as NoticeSrv
	
	participant "Authorization Server\n<$AzureActiveDirectory,scale=0.5,color=DodgerBlue>" as AzureAD
	participant "Storage\n<$AzureBlobStorage,scale=0.5,color=DodgerBlue>" as AzureST
	
	participant "Redis\n<$AzureRedisCache,scale=0.5,color=DodgerBlue>" as NoticeCache
	participant "MongoDB\n<$AzureCosmosDb,scale=0.5,color=DodgerBlue>" as NoticeDB
	
	participant "Preset Topic\n<$AzureEventHub,scale=0.5,color=DodgerBlue>" as NoticeTpc
end box

participant "Nodo" as Nodo